=== EBISPOT/ejprd-metadata-models/EJPRD-model-repository/ejprd_metadata_model/ejprd_metadata_model_publisher/metadata_model/metadata_models/json_schema/registry.json
{
  "$id" : "registry.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Rare disease registry dataset",
  "description": "A schema to describe a dataset of patients, cohorts or biomaterials from a registry",
  "required": [
    "@id",
    "@type"
  ],
  "properties": {
    "@id": {
      "description": "a primary identifier for the registry",
      "type": "string",
      "example": "https://www.pcdregistry.eu/"
    },
    "@type": {
      "description": "the primary type for this registry",
      "type": "string",
      "example" : "PatientRegistryDataset",
      "enum": [
        "PatientRegistryDataset", "BiobankDataset"
      ]
    },
    "name": {
      "description": "a name or short description for the registry",
      "type": "string",
      "example" : "PDC registry"
    },
    "description": {
      "description": "A description for the registry",
      "type": "string",
      "example" : "PDC registry"
    },
    "homepage": {
      "description": "The primary URL for the homepage of the registry",
      "type": "string",
      "example" : "https://www.pcdregistry.eu/",
      "format" :"url"
    },
    "publisher": {
      "description": "The primary organisation responsible for publishing and maintaining the registry",
      "$ref": "organisation.json"
    },
    "theme": {
      "description": "The primary diseases associated with the dataset",
      "type": "array",
      "items": {
        "$ref": "vocabulary_code.json"
      }
    },
    "disease_cases": {
      "description": "Information about the individual cases described in the registry",
      "type": "array",
      "items": {
        "$ref": "case.json"
      }
    }
  }
}

=== EBISPOT/ejprd-metadata-models/EJPRD-model-repository/ejprd_metadata_model/ejprd_metadata_model_publisher/examples/registry-1.json
{
  "@id": "https://www.pcdregistry.eu/",
  "@type": "PatientRegistryDataset",
  "name": "PCD Registry",
  "disease_cases": [
    {
      "disease_code": [
        {"@id": "http://www.orpha.net/ORDO/Orphanet_137628"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_363250"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275742"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_244"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_98861"}
      ]
    }
  ],
  "publisher": [
    {
      "name": "University Hospital Muenster of the Westfalian University of Muenster (WWU)",
      "location": {
        "city": "D-48149 Muenster",
        "country": "Germany"
      }
    }
   ]
}

=== EBISPOT/ejprd-metadata-models/EJPRD-model-repository/ejprd_metadata_model/ejprd_metadata_model_publisher/examples/registry-2.json
{
  "@id": "http://www.reseau-htap.fr/",
  "@type": "PatientRegistryDataset",
  "name": "FPHR",
   "disease_cases": [
    {
      "disease_code": [
        {"@id": "http://www.orpha.net/ORDO/Orphanet_70591"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275786"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275777"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_422"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275766"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_182090"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275791"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275828"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275803"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275798"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275808"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275813"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275823"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275837"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_275844"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_431353"},
        {"@id": "http://www.orpha.net/ORDO/Orphanet_71198"}
      ]
    }
  ],
  "publisher": [
    {
      "name": "AP-HP Hôpital Bicêtre Université Paris-Sud",
      "location": {
        "city": "94275 Le Kremlin-Bicêtre",
        "country": "France"
      }
    }
   ]
}
